// Auto-generated by 03b_learn_mutation_axes.py
// Mutation axes learned from PCA on optimized parameters

#pragma once
#include <map>
#include <string>
#include <vector>

struct MutationAxis {
    std::string name;
    float varianceExplained;
    std::map<std::string, float> loadings;
};

inline std::map<std::string, std::vector<MutationAxis>> getMutationAxes() {
    std::map<std::string, std::vector<MutationAxis>> axes;

    // kicks (5 axes, 98.5% variance)
    axes["kicks"] = {
        {"peso", 0.374f, {{"bodyDecay", 34.858403f}, {"clickAmount", 1.028961f}, {"driveAmount", 0.900643f}, {"pitchDrop", -0.027028f}, {"pitchDropTime", 24.006338f}, {"subFreq", 0.026611f}, {"subLevel", 0.739039f}, {"tailLength", 15.741315f}}},
        {"punch", 0.269f, {{"clickAmount", -1.55073f}, {"driveAmount", 2.346127f}, {"pitchDrop", 0.146071f}, {"pitchDropTime", 15.999644f}, {"subFreq", 0.019118f}, {"subLevel", 1.909867f}}},
        {"longitud", 0.169f, {{"bodyDecay", 14.509567f}, {"clickAmount", -0.215095f}, {"driveAmount", 7.655997f}, {"pitchDropTime", -20.904538f}, {"subFreq", -0.039261f}, {"tailLength", 5.446458f}}},
        {"brillo", 0.137f, {{"clickAmount", 0.293323f}, {"pitchDrop", -0.074967f}, {"pitchDropTime", -37.639979f}, {"subFreq", 0.025768f}, {"subLevel", 3.087781f}, {"tailLength", -4.485541f}}},
        {"drive", 0.036f, {{"bodyDecay", -21.981504f}, {"driveAmount", 5.923221f}, {"pitchDrop", -0.084937f}, {"pitchDropTime", 24.611946f}, {"subFreq", 0.032907f}, {"subLevel", -0.820735f}, {"tailLength", -8.253909f}}},
    };

    // snares (5 axes, 98.3% variance)
    axes["snares"] = {
        {"cuerpo", 0.367f, {{"bodyDecay", -2.520941f}, {"bodyFreq", -0.011666f}, {"noiseAmount", -1.642073f}, {"noiseColor", -1.222452f}, {"noiseDecay", -30.037916f}, {"snapAmount", 1.833276f}, {"wireAmount", -0.860488f}}},
        {"snap", 0.288f, {{"bodyDecay", 12.245885f}, {"bodyFreq", 0.004331f}, {"noiseAmount", -1.466069f}, {"noiseColor", 1.624041f}, {"noiseDecay", -17.875342f}, {"wireAmount", 1.536682f}}},
        {"ruido", 0.223f, {{"bodyFreq", -0.030821f}, {"noiseAmount", -0.440212f}, {"noiseColor", -0.528955f}, {"noiseDecay", 12.398487f}, {"snapAmount", -0.350931f}, {"wireAmount", 4.187047f}}},
        {"tono", 0.082f, {{"bodyDecay", 2.796443f}, {"bodyFreq", -0.021972f}, {"noiseAmount", 2.058047f}, {"noiseColor", 1.411506f}, {"snapAmount", 1.703784f}, {"wireAmount", -1.035631f}}},
        {"duracion", 0.023f, {{"bodyDecay", -5.354436f}, {"bodyFreq", 0.023692f}, {"noiseColor", 0.548589f}, {"noiseDecay", 10.762795f}, {"snapAmount", 1.912686f}, {"wireAmount", 3.159355f}}},
    };

    // hihats (2 axes, 87.6% variance)
    axes["hihats"] = {
        {"apertura", 0.527f, {{"decay", 17.738007f}, {"freqRange", -0.001538f}, {"metallic", 0.676799f}, {"noiseColor", -1.069137f}, {"ringAmount", 1.664398f}, {"tone", -1.366589f}}},
        {"brillo", 0.348f, {{"decay", -10.177664f}, {"freqRange", 0.002716f}, {"metallic", 2.18071f}, {"noiseColor", -0.842384f}, {"ringAmount", -0.780122f}, {"tone", -1.027219f}}},
    };

    // claps (2 axes, 77.8% variance)
    axes["claps"] = {
        {"duracion", 0.476f, {{"decay", 98.114286f}, {"noiseColor", 0.960725f}, {"numLayers", 0.164181f}, {"spread", 1.737804f}, {"thickness", 4.966997f}, {"transientSnap", -1.323506f}}},
        {"espacialidad", 0.302f, {{"decay", 11.494857f}, {"noiseColor", 1.685673f}, {"numLayers", 0.747775f}, {"spread", -1.239382f}, {"transientSnap", 2.789933f}}},
    };

    // percs (3 axes, 95.9% variance)
    axes["percs"] = {
        {"tono", 0.623f, {{"decay", -25.492007f}, {"freq", 0.00063f}, {"metallic", -1.696122f}, {"noiseMix", 2.102844f}, {"pitchDrop", -0.054453f}, {"woodiness", 1.253937f}}},
        {"duracion", 0.250f, {{"decay", 36.538731f}, {"freq", 0.000443f}, {"noiseMix", 0.45812f}, {"pitchDrop", 0.092755f}, {"woodiness", 1.986311f}}},
        {"ruido", 0.087f, {{"decay", 9.038029f}, {"freq", 0.001343f}, {"metallic", 1.618056f}, {"noiseMix", -0.567817f}, {"pitchDrop", -0.044231f}, {"woodiness", -0.584416f}}},
    };

    // 808s (4 axes, 97.4% variance)
    axes["808s"] = {
        {"profundidad", 0.548f, {{"distortion", 1.679657f}, {"filterEnvAmt", 1.295009f}, {"punchiness", -1.244756f}, {"reeseMix", 5.930727f}, {"slide", -1.49498f}, {"sustain", -6.68588f}}},
        {"sustain", 0.218f, {{"filterEnvAmt", -1.543779f}, {"freq", 0.062094f}, {"punchiness", -0.479461f}, {"reeseMix", -3.461153f}, {"slide", -0.503535f}, {"sustain", -8.168355f}}},
        {"distorsion", 0.137f, {{"distortion", -0.466874f}, {"filterEnvAmt", 1.131552f}, {"freq", 0.018045f}, {"punchiness", 0.722734f}, {"reeseMix", 5.214768f}, {"slide", 2.232563f}, {"sustain", -11.711539f}}},
        {"slide", 0.071f, {{"distortion", -0.971533f}, {"filterEnvAmt", -0.254951f}, {"freq", 0.029497f}, {"punchiness", -0.918276f}, {"reeseMix", 8.603248f}, {"slide", 0.579749f}, {"sustain", 12.497693f}}},
    };

    // leads (5 axes, 98.1% variance)
    axes["leads"] = {
        {"registro", 0.417f, {{"attack", 54.852211f}, {"brightness", -0.87792f}, {"decay", 84.652763f}, {"detune", -21.374034f}, {"freq", 0.002366f}, {"pulseWidth", -2.208499f}, {"vibratoRate", -0.14261f}}},
        {"detune", 0.186f, {{"attack", 28.397108f}, {"brightness", -0.622975f}, {"decay", -83.821415f}, {"detune", 11.655957f}, {"freq", 0.003351f}, {"pulseWidth", 1.679178f}, {"vibratoRate", 0.27179f}}},
        {"forma", 0.173f, {{"attack", 26.334755f}, {"brightness", 1.443754f}, {"decay", 90.942158f}, {"detune", 10.994359f}, {"freq", 0.000824f}, {"pulseWidth", -4.050194f}, {"vibratoRate", 0.162743f}}},
        {"ataque", 0.121f, {{"attack", 16.377557f}, {"decay", 163.535803f}, {"detune", -5.970478f}, {"freq", -0.000797f}, {"pulseWidth", 5.315643f}, {"vibratoRate", 0.132418f}}},
        {"duracion", 0.084f, {{"attack", 63.854222f}, {"brightness", -0.2764f}, {"detune", 33.473468f}, {"freq", -0.001322f}, {"pulseWidth", 0.869467f}, {"vibratoRate", -0.180287f}}},
    };

    // plucks (3 axes, 94.4% variance)
    axes["plucks"] = {
        {"registro", 0.427f, {{"bodyResonance", -1.238854f}, {"brightness", 7.528499f}, {"damping", -17.005528f}, {"decay", 5308.078619f}, {"freq", 0.006713f}}},
        {"duracion", 0.273f, {{"bodyResonance", 12.277938f}, {"brightness", 2.804025f}, {"damping", 90.333967f}, {"decay", -2369.735247f}, {"freq", 0.00077f}}},
        {"brillo", 0.244f, {{"bodyResonance", 13.346763f}, {"brightness", -1.805952f}, {"damping", -29.103915f}, {"decay", 9925.419463f}, {"freq", -0.002418f}}},
    };

    // pads (4 axes, 98.8% variance)
    axes["pads"] = {
        {"registro", 0.485f, {{"attack", 3.834595f}, {"chorusAmount", 2.406082f}, {"filterSweep", 1.53405f}, {"freq", -0.000871f}, {"release", 2.708194f}, {"warmth", -6.810816f}}},
        {"ataque", 0.250f, {{"attack", -0.843877f}, {"chorusAmount", -0.451154f}, {"detune", 87.416545f}, {"filterSweep", 0.410195f}, {"freq", 0.010113f}, {"release", 0.286239f}, {"warmth", -15.789962f}}},
        {"release", 0.157f, {{"attack", 1.26411f}, {"chorusAmount", -1.588452f}, {"detune", 59.469517f}, {"filterSweep", 0.786401f}, {"freq", -0.002781f}, {"warmth", 47.195265f}}},
        {"detune", 0.095f, {{"attack", -1.380912f}, {"chorusAmount", 2.780184f}, {"detune", -13.235192f}, {"filterSweep", -1.322033f}, {"freq", 0.005679f}, {"release", 1.386086f}, {"warmth", 33.090067f}}},
    };

    // textures (3 axes, 84.5% variance)
    axes["textures"] = {
        {"densidad", 0.468f, {{"brightness", 1.359342f}, {"density", -3.762333f}, {"grainSize", 1611.915922f}, {"movement", 2.264824f}, {"noiseColor", 1.175943f}, {"spectralTilt", -0.854321f}}},
        {"brillo", 0.211f, {{"brightness", 3.019277f}, {"density", 0.577955f}, {"grainSize", -1910.374444f}, {"movement", 0.362734f}, {"noiseColor", -1.040737f}, {"spectralTilt", -0.93156f}}},
        {"movimiento", 0.167f, {{"brightness", 1.74476f}, {"density", 5.448454f}, {"grainSize", 1814.182641f}, {"movement", -2.398649f}, {"noiseColor", 0.617324f}, {"spectralTilt", -0.341051f}}},
    };

    return axes;
}
